name: Checkmarx AST Scan
on:
 push:
  branches:
   - main
   - master
   - dev
  
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Checkmarx AST Github Action
     # You may pin to the exact commit or the version.
     # uses: Checkmarx/ast-github-action@e216d56a6535d1921fae7e88d50dd580892ed3ef
     uses: Checkmarx/ast-github-action@2.0.14
     with:
       # Provide the AST portal URL
       base_uri: https://eu.ast.checkmarx.net
       # Provide the Tenant for AST portal URL
       cx_tenant: nfr_redshift_nfr
       # Client ID for AST portal authentication
       cx_client_id: ${{ secrets.CLIENT_ID }}
       # Secret key for AST portal authentication
       cx_client_secret: ${{ secrets.SECRET }}
       # Select a Checkmarx Project Name
       # optional, default is ${{ github.repository }}
       project_name: CxONE_WebGoat
       # Branch name
       # optional, default is ${{ github.head_ref || github.ref }}
       branch: main
